version: "3.9"

services:
  php:
    container_name: php
    build: ./docker/php-fpm
    working_dir: /app
    volumes:
      - .:/app

  nginx:
    build: ./docker/nginx
    container_name: nginx
    working_dir: /app
    volumes:
      - .:/app 
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/localhost+2.pem:/etc/nginx/localhost+2.pem
      - ./docker/nginx/localhost+2-key.pem:/etc/nginx/localhost+2-key.pem
    ports:
      - "443:443"
      - "80:80"